export { default as App } from './App';
export { default as Home } from './Home';
export { default as Template} from './Template';
export { default as Edit } from './Edit';
export { default as TemplateEdit } from './TemplateEdit';
export { default as CssView } from './CssView';
export { default as About } from './About';
export { default as Footer } from './Footer';
export { default as Resource } from './Resource';
export { default as NotFound } from './NotFound';
export { defautl as Info } from './Tutorial';